version: "3"
services:
  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    command: python Project_Manage_System/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "10200:8000"