# Generated by Django 3.1.4 on 2021-06-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0002_auto_20210528_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembers',
            name='owner',
        ),
    ]
