# Generated by Django 3.1.4 on 2021-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0005_projects_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
