# Generated by Django 3.1.4 on 2021-06-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0006_auto_20210617_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pms_index.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ListCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pms_index.workspacelist')),
            ],
        ),
    ]
