# Generated by Django 3.1.4 on 2021-07-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0007_listcard_workspacelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listcard',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='workspacelist',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
