# Generated by Django 3.1.4 on 2021-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0008_auto_20210709_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspacelist',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
