# Generated by Django 3.1.4 on 2021-07-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0009_auto_20210713_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcard',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='workspacelist',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
