# Generated by Django 3.1.4 on 2021-07-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0010_auto_20210713_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcard',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='workspacelist',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
