# Generated by Django 3.1.4 on 2021-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0011_auto_20210713_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='status',
            field=models.CharField(default='active', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspacelist',
            name='status',
            field=models.CharField(default='active', max_length=10),
            preserve_default=False,
        ),
    ]
