# Generated by Django 3.1.4 on 2021-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_index', '0013_auto_20210714_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcard',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspacelist',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
